name: "test"

on:
  pull_request:

jobs:
  test:
    environment: test
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: "0"
          fetch-tags: true

      - name: Get deno version
        id: get_deno_version
        run: echo "dvmrc=$(cat .dvmrc)" >> "$GITHUB_OUTPUT"

      - uses: denoland/setup-deno@v1
        with:
          deno-version: "${{ steps.get_deno_version.outputs.dvmrc }}"

      - name: Create SECRET_KEY file
        run: echo "${{ secrets.SECRET_KEY }}" > "SECRET_KEY"

      - name: "test"
        run: |
          echo "$SHELL"
          help
        # run: "deno task test"
